### ISSUE TITLE
You ran out of lives!

### ISSUE THREAD

**Issue by SeaBa55** [AlecWGreene/MSU-Project3-Four-Horsemen#99]
Alert for "You ran out of lives!" is stuck in an infinite loop, which forces the user to refresh the page to continue as there are no easy methods of ending exiting the page if the bug is present.

**Comment by AlecWGreene** [comment]
We can refactor the end game screens to be shared between victory and defeat states, consolidating the UX flows. Then we can have the modal redirect offer a button to the home screen.
